language: python
deploy:
  provider: pypi
  user: bushono
  password:
    secure: DJ8O7sKENff7pAVKMUIBwesfGINkkyxoxMiE56Rf1kZcNtLA3/RnmmmRZddzpq31C+YLKtbjbNL/wFORnLN2FRFVoFg9rLH//hDL38TMCF7TQCDq/dyFGUGEHWOXwfh3LtTpbFkz6sxlv7Q8PGXBfAuQi5YbxKnjC03KYfeqjHKu619tYzReIKblBADgL9T2oMr1gTIOymq18Ud6bgeBjpJFtuNAhKvbhDBOxRDsSn89XyzwOMPEkawrpLwYj2dH0/6M1PGw8zhAd2qgyXdNLMlfSYNUFHcO1GMX2aRfBpPvC/nUlWoCelSX0KGLjUB5nlKE0WpqQVzlUcy6IL9AIaccVGvdymfObq1Qd5N0vlVTfvgK2xQG6QWPmUxtywM3KgtRBkx+smB0HdCCpTpo2bfX4zrCaYYvd6htqcK6F0KCmxI45l1AGaWkCVxTtTbsSVgyKNQckJHBa6VLD3JMvn0voVi58xR9DKPg0K3EIPRmNPilsJ06zTXhB1adonRfYlixSAvVmG/46BGy3l0r6R8YLWv9iAm/B9B7p+P7I6vJSaoCL8WV6aD/+DYgK1/J9tCWuNH0cuH++fqKd9Za0Q3wRhFdtPLqzHD75fv2rnS/2cwwtHpkWUtS6i8oC9OflvLrtUbv1oP9UDv8s7gJqUmalUrw07Q80od9xxHKMhM=
